FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app
COPY ./static ./static
COPY ./.env ./.env
COPY ./run_consumer.py ./run_consumer.py

